repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        entry: uv run task lint-check
        pass_filenames: false
      - id: mypy
        name: mypy
        language: system
        entry: uv run task type-check
        pass_filenames: false
